name: Rust

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: Rename for Windows (Optional)
      if: runner.os == 'Linux'
      run: |
        cd target/release/
        for file in *; do
          if [[ -f "$file" && -x "$file" && ! "$file" =~ \.exe$ ]]; then
            mv "$file" "$file.exe"
          fi
        done
        ls -l
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.SELF_TOKEN }}
        files:
          ./target/release/*.exe
        tag_name: ${{ steps.tag.outputs.tag }}
      
