name: Rust

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Install MinGW-w64
      run: sudo apt-get update && sudo apt-get install -y mingw-w64
    - name: Add Rust target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build (Release - Windows)
      run: cargo build --release --verbose --target x86_64-pc-windows-gnu
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.SELF_TOKEN }}
        files:
          ./target/x86_64-pc-windows-gnu/release/*.exe
        tag_name: ${{ steps.tag.outputs.tag }}
      
