name: Rust

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.SELF_TOKEN }}
        files:
          ./target/debug/json_converter.exe
        tag_name: ${{ steps.tag.outputs.tag }}
      
